pgdb:
   container_name: pgdb
   image: postgres
   environment:
   - POSTGRES_USER=ttrss
   - POSTGRES_PASSWORD=ttrss
   - POSTGRES_DB=ttrss
   volumes:
   - ./var/lib/postgresql/data:/var/lib/postgresql/data
ttrss:
   container_name: ttrss
   image: x86dev/docker-ttrss
   links:
      - pgdb:db
   volumes:
      - ./tt-rss_:/var/www/html:rw
   ports:
      - 9108:80
